/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jobdataportal;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String url = "https://weworkremotely.com";
        JobExtractorWWR service = new JobExtractorWWR();
        for (JobData job : service.getJobObjects(url)) {
            System.out.println(job.toString());
        }
    }
}
