/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jobdataportal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JobExtractorService service = new JobExtractorService();
        for (JobData job : service.getWWRJobs()) {
            System.out.println(job.toString());
        }
    }
}
